# Generated by Django 4.1.3 on 2024-09-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=250)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='lwlapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_storys', to='lwlapi.individual')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_related_storys', to='lwlapi.story')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lwlapi.user'),
        ),
        migrations.CreateModel(
            name='GroupStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_storys', to='lwlapi.group')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_related_storys', to='lwlapi.story')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lwlapi.user'),
        ),
    ]
