# Generated by Django 4.1.3 on 2024-08-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lwlapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='individual',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
